### ISSUE TITLE
Not Working, But have a fix

### ISSUE THREAD

**Issue by stephenwebb97** [caelwithcats/binge-on-linux#1]
Hey your add on isn't working anymore, but I have found a fix,

Just update in content.js in the source.zip from

`localStorage.setItem('ares-can-use-high-drm','{ "value":true }');`

to

`
{
  let temp = new Date();
  temp.setFullYear((new Date()).getFullYear() + 1)
  localStorage.setItem('ares-can-use-high-drm','{ "value":true }');
  localStorage.setItem('ares-playback-details','{"value":{"all":{"fairPlayAvcHigh":"","playReadyAvcHigh":"","playReadyAvcLow":"","playReadyHevcHigh":"","playReadyHevcLow":"","widevineAvcHigh":"","widevineAvcLow":"","widevineHevcHigh":"","widevineHevcLow":""},"canPlayHighDrm":true,"canPlayHevc":false},"valueExpiresIn":"'+temp.toJSON()+'"}');
}
`

Thanks Heaps

**Comment by masterneko** [comment]
Sorry for the late reply; I didn't see your comment until today. but yes I've been aware that this extension hasn't been working for a lot people now.

Thanks for your contribution. 🙂
